version: '3.1'

services:
  db:
    build: .
    container_name: mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: mudar123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
