name: Ensure Code Quality

env:
  LANG: "en_US.UTF-8"
  ImageOS: ubuntu-latest
  NODE_ENV: development

on: pull_request

jobs:
  lint-and-test:
    name: Run linter and tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [18]
    steps:
      - name: Checkout Github repo
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install Yarn
        run: npm install -g yarn
      - name: Install packages
        run: yarn install
      - name: Run Tests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Uninstall Yarn
        if: always()
        run: npm uninstall -g yarn
